const QUESTIONS = [
  { id: 1, page: "page1", number: 1, question: "詩を楽しむ", answer: "詩", reading: "し", priority: "A" },
  { id: 2, page: "page1", number: 2, question: "言葉のつかい方", answer: "言葉", reading: "ことば", priority: "A" },
  { id: 3, page: "page1", number: 3, question: "毎日の学習", answer: "学習", reading: "がくしゅう", priority: "A" },
  { id: 4, page: "page1", number: 4, question: "デザインに着目する", answer: "着目", reading: "ちゃくもく", priority: "A" },
  { id: 5, page: "page1", number: 5, question: "新しく登場する", answer: "登場", reading: "とうじょう", priority: "A" },
  { id: 6, page: "page1", number: 6, question: "人物のようす", answer: "人物", reading: "じんぶつ", priority: "B" },
  { id: 7, page: "page1", number: 7, question: "気持ちをあらわす", answer: "気持ち", reading: "きもち", priority: "B" },
  { id: 8, page: "page1", number: 8, question: "旅の日記", answer: "旅", reading: "たび", priority: "B" },
  { id: 9, page: "page1", number: 9, question: "黄金にかがやく", answer: "黄金", reading: "おうごん", priority: "B" },
  { id: 10, page: "page1", number: 10, question: "話を始める", target: "始める", answer: "始める", reading: "はじめる", priority: "B" },
  { id: 11, page: "page1", number: 11, question: "白一色の山", target: "白一色", answer: "白一色", reading: "しろいっしょく", priority: "B" },
  { id: 12, page: "page1", number: 12, question: "赤くこう葉した木", target: "こう葉", answer: "紅葉", reading: "こうよう", priority: "B" },
  { id: 13, page: "page1", number: 13, question: "ピアノを習う", target: "習う", answer: "習う", reading: "ならう", priority: "B" },
  { id: 14, page: "page1", number: 14, question: "ドレスを着る", target: "着る", answer: "着る", reading: "きる", priority: "B" },
  { id: 15, page: "page1", number: 15, question: "山に登る", target: "登る", answer: "登る", reading: "のぼる", priority: "B" },
  { id: 16, page: "page1", number: 16, question: "たから物をさがす", target: "たから物", answer: "宝物", reading: "たからもの", priority: "B" },
  { id: 17, page: "page1", number: 17, question: "本を所持する", target: "所持", answer: "所持", reading: "しょじ", priority: "B" },
  { id: 18, page: "page1", number: 18, question: "旅行をする", answer: "旅行", reading: "りょこう", priority: "B" },
  { id: 19, page: "page1", number: 19, question: "年始のあいさつ", answer: "年始", reading: "ねんし", priority: "B" },
  { id: 20, page: "page1", number: 20, question: "家に着く", target: "着く", answer: "着く", reading: "つく", priority: "B" },

  { id: 21, page: "page2", number: 1, question: "前に進む", target: "進む", answer: "進む", reading: "すすむ", priority: "A" },
  { id: 22, page: "page2", number: 2, question: "今日のよてい", target: "今日", answer: "今日", reading: "きょう", priority: "A" },
  { id: 23, page: "page2", number: 3, question: "体が動く", target: "動く", answer: "動く", reading: "うごく", priority: "A" },
  { id: 24, page: "page2", number: 4, question: "深い海", target: "深い", answer: "深い", reading: "ふかい", priority: "A" },
  { id: 25, page: "page2", number: 5, question: "母の様子", answer: "様子", reading: "ようす", priority: "A" },
  { id: 26, page: "page2", number: 6, question: "一人で電車にのる", target: "一人", answer: "一人", reading: "ひとり", priority: "B" },
  { id: 27, page: "page2", number: 7, question: "タイヤに空気を入れる", answer: "空気", reading: "くうき", priority: "B" },
  { id: 28, page: "page2", number: 8, question: "物語を書く", answer: "物語", reading: "ものがたり", priority: "B" },
  { id: 29, page: "page2", number: 9, question: "つぎの場面", target: "場面", answer: "場面", reading: "ばめん", priority: "B" },
  { id: 30, page: "page2", number: 10, question: "二人で出かける", target: "二人", answer: "二人", reading: "ふたり", priority: "B" },
  { id: 31, page: "page2", number: 11, question: "自分の顔", answer: "顔", reading: "かお", priority: "B" },
  { id: 32, page: "page2", number: 12, question: "大きな声を出す", answer: "声", reading: "こえ", priority: "B" },
  { id: 33, page: "page2", number: 13, question: "しつもんに答える", target: "答える", answer: "答える", reading: "こたえる", priority: "B" },
  { id: 34, page: "page2", number: 14, question: "力が弱い", target: "弱い", answer: "弱い", reading: "よわい", priority: "B" },
  { id: 35, page: "page2", number: 15, question: "近くの店に行く", target: "近く", answer: "近く", reading: "ちかく", priority: "B" },
  { id: 36, page: "page2", number: 16, question: "むかしを思い出す", target: "思い出す", answer: "思い出す", reading: "おもいだす", priority: "B" },
  { id: 37, page: "page2", number: 17, question: "校ていを行進する", target: "行進", answer: "行進", reading: "こうしん", priority: "B" },
  { id: 38, page: "page2", number: 18, question: "クラブ活動をする", answer: "活動", reading: "かつどう", priority: "B" },
  { id: 39, page: "page2", number: 19, question: "池の水深をしらべる", target: "水深", answer: "水深", reading: "すいしん", priority: "B" },
  { id: 40, page: "page2", number: 20, question: "との様につかえる", target: "様", answer: "様", reading: "さま", priority: "B" },

  { id: 41, page: "page3", number: 1, question: "図書館の本", answer: "図書館", reading: "としょかん", priority: "A" },
  { id: 42, page: "page3", number: 2, question: "番号をつける", answer: "番号", reading: "ばんごう", priority: "A" },
  { id: 43, page: "page3", number: 3, question: "くわしく調べる", target: "調べる", answer: "調べる", reading: "しらべる", priority: "A" },
  { id: 44, page: "page3", number: 4, question: "キーボードを使う", target: "使う", answer: "使う", reading: "つかう", priority: "A" },
  { id: 45, page: "page3", number: 5, question: "問いと答え", target: "問い", answer: "問い", reading: "とい", priority: "A" },
  { id: 46, page: "page3", number: 6, question: "言葉の意味", answer: "意味", reading: "いみ", priority: "B" },
  { id: 47, page: "page3", number: 7, question: "湖が見える", answer: "湖", reading: "みずうみ", priority: "B" },
  { id: 48, page: "page3", number: 8, question: "漢字を習う", answer: "漢字", reading: "かんじ", priority: "B" },
  { id: 49, page: "page3", number: 9, question: "自由に話す", answer: "自由", reading: "じゆう", priority: "B" },
  { id: 50, page: "page3", number: 10, question: "温かいお茶", target: "温かい", answer: "温かい", reading: "あたたかい", priority: "B" },
  { id: 51, page: "page3", number: 11, question: "話を考える", target: "考える", answer: "考える", reading: "かんがえる", priority: "B" },
  { id: 52, page: "page3", number: 12, question: "新聞を読む", target: "読む", answer: "読む", reading: "よむ", priority: "B" },
  { id: 53, page: "page3", number: 13, question: "古い館", answer: "館", reading: "やかた", priority: "B" },
  { id: 54, page: "page3", number: 14, question: "肉を調理する", answer: "調理", reading: "ちょうり", priority: "B" },
  { id: 55, page: "page3", number: 15, question: "はさみを使用する", answer: "使用", reading: "しよう", priority: "B" },
  { id: 56, page: "page3", number: 16, question: "学問にはげむ", target: "学問", answer: "学問", reading: "がくもん", priority: "B" },
  { id: 57, page: "page3", number: 17, question: "ケーキを味わう", target: "味わう", answer: "味わう", reading: "あじわう", priority: "B" },
  { id: 58, page: "page3", number: 18, question: "青くすんだ湖水", answer: "湖水", reading: "こすい", priority: "B" },
  { id: 59, page: "page3", number: 19, question: "名前の由来", answer: "由来", reading: "ゆらい", priority: "B" },
  { id: 60, page: "page3", number: 20, question: "体温が高い", answer: "体温", reading: "たいおん", priority: "B" },

  { id: 61, page: "page4", number: 1, question: "あま酒をのむ", target: "あま酒", answer: "甘酒", reading: "あまざけ", priority: "A" },
  { id: 62, page: "page4", number: 2, question: "問題に答える", target: "問題", answer: "問題", reading: "もんだい", priority: "A" },
  { id: 63, page: "page4", number: 3, question: "新発売の本", target: "新発売", answer: "新発売", reading: "しんはつばい", priority: "A" },
  { id: 64, page: "page4", number: 4, question: "文章を読む", answer: "文章", reading: "ぶんしょう", priority: "A" },
  { id: 65, page: "page4", number: 5, question: "平気な顔をする", answer: "平気", reading: "へいき", priority: "A" },
  { id: 66, page: "page4", number: 6, question: "みんなで決める", target: "決める", answer: "決める", reading: "きめる", priority: "B" },
  { id: 67, page: "page4", number: 7, question: "今日の出来事", answer: "出来事", reading: "できごと", priority: "B" },
  { id: 68, page: "page4", number: 8, question: "ペンを落とす", target: "落とす", answer: "落とす", reading: "おとす", priority: "B" },
  { id: 69, page: "page4", number: 9, question: "相手につたえる", target: "相手", answer: "相手", reading: "あいて", priority: "B" },
  { id: 70, page: "page4", number: 10, question: "洋服を買う", answer: "洋服", reading: "ようふく", priority: "B" },
  { id: 71, page: "page4", number: 11, question: "人形であそぶ", target: "人形", answer: "人形", reading: "にんぎょう", priority: "B" },
  { id: 72, page: "page4", number: 12, question: "話の中心", answer: "中心", reading: "ちゅうしん", priority: "B" },
  { id: 73, page: "page4", number: 13, question: "お母さんと出かける", target: "母さん", answer: "母さん", reading: "かあさん", priority: "B" },
  { id: 74, page: "page4", number: 14, question: "日本酒をつくる", answer: "日本酒", reading: "にほんしゅ", priority: "B" },
  { id: 75, page: "page4", number: 15, question: "平たい石", target: "平たい", answer: "平たい", reading: "ひらたい", priority: "B" },
  { id: 76, page: "page4", number: 16, question: "かたい決意をする", target: "決意", answer: "決意", reading: "けつい", priority: "B" },
  { id: 77, page: "page4", number: 17, question: "用事をすませる", target: "用事", answer: "用事", reading: "ようじ", priority: "B" },
  { id: 78, page: "page4", number: 18, question: "岩が落下する", answer: "落下", reading: "らっか", priority: "B" },
  { id: 79, page: "page4", number: 19, question: "手相を見る", answer: "手相", reading: "てそう", priority: "B" },
  { id: 80, page: "page4", number: 20, question: "平らな道", target: "平ら", answer: "平ら", reading: "たいら", priority: "B" },

  { id: 81, page: "page5", number: 1, question: "次の月曜日", target: "次", answer: "次", reading: "つぎ", priority: "A" },
  { id: 82, page: "page5", number: 2, question: "広い所にすわる", target: "所", answer: "所", reading: "ところ", priority: "A" },
  { id: 83, page: "page5", number: 3, question: "県道ぞいの店", target: "県道", answer: "県道", reading: "けんどう", priority: "A" },
  { id: 84, page: "page5", number: 4, question: "有名な人", target: "有名", answer: "有名", reading: "ゆうめい", priority: "A" },
  { id: 85, page: "page5", number: 5, question: "氷がとける", target: "氷", answer: "氷", reading: "こおり", priority: "A" },
  { id: 86, page: "page5", number: 6, question: "六十秒を数える", target: "六十秒", answer: "六十秒", reading: "ろくじゅうびょう", priority: "B" },
  { id: 87, page: "page5", number: 7, question: "農家の人", target: "農家", answer: "農家", reading: "のうか", priority: "B" },
  { id: 88, page: "page5", number: 8, question: "仕事をする", target: "仕事", answer: "仕事", reading: "しごと", priority: "B" },
  { id: 89, page: "page5", number: 9, question: "野球のれんしゅう", target: "野球", answer: "野球", reading: "やきゅう", priority: "B" },
  { id: 90, page: "page5", number: 10, question: "ゆうびん局の前", target: "局", answer: "局", reading: "きょく", priority: "B" },
  { id: 91, page: "page5", number: 11, question: "朝食をとる", target: "朝食", answer: "朝食", reading: "ちょうしょく", priority: "B" },
  { id: 92, page: "page5", number: 12, question: "早朝におきる", target: "早朝", answer: "早朝", reading: "そうちょう", priority: "B" },
  { id: 93, page: "page5", number: 13, question: "日光に当てる", target: "日光", answer: "日光", reading: "にっこう", priority: "B" },
  { id: 94, page: "page5", number: 14, question: "一分がすぎる", target: "一分", answer: "一分", reading: "いっぷん", priority: "B" },
  { id: 95, page: "page5", number: 15, question: "次回につづく", target: "次回", answer: "次回", reading: "じかい", priority: "B" },
  { id: 96, page: "page5", number: 16, question: "時間と場所", target: "場所", answer: "場所", reading: "ばしょ", priority: "B" },
  { id: 97, page: "page5", number: 17, question: "お金が有る", target: "有る", answer: "有る", reading: "ある", priority: "B" },
  { id: 98, page: "page5", number: 18, question: "大きな氷山", target: "氷山", answer: "氷山", reading: "ひょうざん", priority: "B" },
  { id: 99, page: "page5", number: 19, question: "王に仕える", target: "仕える", answer: "仕える", reading: "つかえる", priority: "B" },
  { id: 100, page: "page5", number: 20, question: "球をなげる", target: "球", answer: "球", reading: "たま", priority: "B" },

  { id: 101, page: "page6", number: 1, question: "全体の数", target: "全体", answer: "全体", reading: "ぜんたい", priority: "A" },
  { id: 102, page: "page6", number: 2, question: "こま遊びをする", target: "遊び", answer: "遊び", reading: "あそび", priority: "A" },
  { id: 103, page: "page6", number: 3, question: "新しい発見", target: "発見", answer: "発見", reading: "はっけん", priority: "A" },
  { id: 104, page: "page6", number: 4, question: "考えを表す", target: "表す", answer: "表す", reading: "あらわす", priority: "A" },
  { id: 105, page: "page6", number: 5, question: "昔の歌", target: "昔", answer: "昔", reading: "むかし", priority: "A" },
  { id: 106, page: "page6", number: 6, question: "世界中の国", target: "世界中", answer: "世界中", reading: "せかいじゅう", priority: "B" },
  { id: 107, page: "page6", number: 7, question: "動く速さ", target: "速さ", answer: "速さ", reading: "はやさ", priority: "B" },
  { id: 108, page: "page6", number: 8, question: "横の長さ", target: "横", answer: "横", reading: "よこ", priority: "B" },
  { id: 109, page: "page6", number: 9, question: "指でつまむ", target: "指", answer: "指", reading: "ゆび", priority: "B" },
  { id: 110, page: "page6", number: 10, question: "上手な絵", target: "上手", answer: "上手", reading: "じょうず", priority: "B" },
  { id: 111, page: "page6", number: 11, question: "大会を行う", target: "行う", answer: "行う", reading: "おこなう", priority: "B" },
  { id: 112, page: "page6", number: 12, question: "元のすがた", target: "元", answer: "元", reading: "もと", priority: "B" },
  { id: 113, page: "page6", number: 13, question: "全てを話す", target: "全て", answer: "全て", reading: "すべて", priority: "B" },
  { id: 114, page: "page6", number: 14, question: "近くの遊園地", target: "遊園地", answer: "遊園地", reading: "ゆうえんち", priority: "B" },
  { id: 115, page: "page6", number: 15, question: "表とうら", target: "表", answer: "表", reading: "おもて", priority: "B" },
  { id: 116, page: "page6", number: 16, question: "へいわな世の中", target: "世", answer: "世", reading: "よ", priority: "B" },
  { id: 117, page: "page6", number: 17, question: "時速五キロメートル", target: "時速", answer: "時速", reading: "じそく", priority: "B" },
  { id: 118, page: "page6", number: 18, question: "横だん歩道", target: "横", answer: "横", reading: "おう", priority: "B" },
  { id: 119, page: "page6", number: 19, question: "北の方角を指す", target: "指す", answer: "指す", reading: "さす", priority: "B" },
  { id: 120, page: "page6", number: 20, question: "考えを発表する", target: "発表", answer: "発表", reading: "はっぴょう", priority: "B" },

  { id: 121, page: "page7", number: 1, question: "鉄のぼう", target: "鉄", answer: "鉄", reading: "てつ", priority: "A" },
  { id: 122, page: "page7", number: 2, question: "生活が安定する", target: "安定", answer: "安定", reading: "あんてい", priority: "A" },
  { id: 123, page: "page7", number: 3, question: "運動会に出る", target: "運動会", answer: "運動会", reading: "うんどうかい", priority: "A" },
  { id: 124, page: "page7", number: 4, question: "予定を立てる", target: "予定", answer: "予定", reading: "よてい", priority: "A" },
  { id: 125, page: "page7", number: 5, question: "六月一日のこと", target: "一日", answer: "一日", reading: "ついたち", priority: "A" },
  { id: 126, page: "page7", number: 6, question: "八十メートル走", target: "走", answer: "走", reading: "そう", priority: "B" },
  { id: 127, page: "page7", number: 7, question: "学校に通う", target: "通う", answer: "通う", reading: "かよう", priority: "B" },
  { id: 128, page: "page7", number: 8, question: "ゆうびんで送る", target: "送る", answer: "送る", reading: "おくる", priority: "B" },
  { id: 129, page: "page7", number: 9, question: "住所とあて名", target: "住所", answer: "住所", reading: "じゅうしょ", priority: "B" },
  { id: 130, page: "page7", number: 10, question: "ねだんが安い", target: "安い", answer: "安い", reading: "やすい", priority: "B" },
  { id: 131, page: "page7", number: 11, question: "はさみを使う", target: "使う", answer: "使う", reading: "つかう", priority: "B" },
  { id: 132, page: "page7", number: 12, question: "こまを回す", target: "回す", answer: "回す", reading: "まわす", priority: "B" },
  { id: 133, page: "page7", number: 13, question: "ボールで遊ぶ", target: "遊ぶ", answer: "遊ぶ", reading: "あそぶ", priority: "B" },
  { id: 134, page: "page7", number: 14, question: "あたりの様子", target: "様子", answer: "様子", reading: "ようす", priority: "B" },
  { id: 135, page: "page7", number: 15, question: "文章を読む", target: "文章", answer: "文章", reading: "ぶんしょう", priority: "B" },
  { id: 136, page: "page7", number: 16, question: "理由をたずねる", target: "理由", answer: "理由", reading: "りゆう", priority: "B" },
  { id: 137, page: "page7", number: 17, question: "ねらいを定める", target: "定める", answer: "定める", reading: "さだめる", priority: "B" },
  { id: 138, page: "page7", number: 18, question: "つくえを運ぶ", target: "運ぶ", answer: "運ぶ", reading: "はこぶ", priority: "B" },
  { id: 139, page: "page7", number: 19, question: "にもつを発送する", target: "発送", answer: "発送", reading: "はっそう", priority: "B" },
  { id: 140, page: "page7", number: 20, question: "町に住む", target: "住む", answer: "住む", reading: "すむ", priority: "B" }
];
